### ISSUE TITLE
problem with importing Solution

### ISSUE THREAD

**Issue by mohamad-alibrahim** [molyom/progressStagePCF#1]
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

**Comment by molyom** [comment]
Hi Mohammad, 
Thank you for reporting the issue. 
I will update it and will let you know when done. 

Kind regards

**Comment by molyom** [comment]
Fixed. you can download it from the last release. (0.0.0.4)
